version: '3'
volumes:
  mysql:
  reviewboard:
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=reviewboard
      - MYSQL_USER=reviewboard
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    volumes:
      - mysql:/var/lib/mysql
  memcached:
    container_name: memcached
    image: memcached:alpine
    restart: always
  reviewboard:
    container_name: reviewboard
    image: easybe/alpine-reviewboard
    restart: always
    links:
      - mysql:db
      - memcached
    ports:
      - 8080:8000
    environment:
      - DB_PASSWORD
      - RB_ADMIN_PASSWORD
      - RB_ADMIN_EMAIL
      - UWSGI_PROCESSES
    volumes:
      - reviewboard:/var/www
